/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.33.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiV2010AccountMessage {
    /// The message text
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// The number of messages used to deliver the message body
    #[serde(rename = "num_segments", skip_serializing_if = "Option::is_none")]
    pub num_segments: Option<String>,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<crate::models::MessageEnumDirection>,
    /// The phone number that initiated the message
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// The phone number that received the message
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    /// The RFC 2822 date and time in GMT that the resource was last updated
    #[serde(rename = "date_updated", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<String>,
    /// The amount billed for the message
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<String>,
    /// The description of the error_code
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    /// The URI of the resource, relative to `https://api.twilio.com`
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<String>,
    /// The number of media files associated with the message
    #[serde(rename = "num_media", skip_serializing_if = "Option::is_none")]
    pub num_media: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::MessageEnumStatus>,
    /// The SID of the Messaging Service used with the message.
    #[serde(rename = "messaging_service_sid", skip_serializing_if = "Option::is_none")]
    pub messaging_service_sid: Option<String>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", skip_serializing_if = "Option::is_none")]
    pub sid: Option<String>,
    /// The RFC 2822 date and time in GMT when the message was sent
    #[serde(rename = "date_sent", skip_serializing_if = "Option::is_none")]
    pub date_sent: Option<String>,
    /// The RFC 2822 date and time in GMT that the resource was created
    #[serde(rename = "date_created", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The error code associated with the message
    #[serde(rename = "error_code", skip_serializing_if = "Option::is_none")]
    pub error_code: Option<i32>,
    /// The currency in which price is measured
    #[serde(rename = "price_unit", skip_serializing_if = "Option::is_none")]
    pub price_unit: Option<String>,
    /// The API version used to process the message
    #[serde(rename = "api_version", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// A list of related resources identified by their relative URIs
    #[serde(rename = "subresource_uris", skip_serializing_if = "Option::is_none")]
    pub subresource_uris: Option<serde_json::Value>,
}

impl ApiV2010AccountMessage {
    pub fn new() -> ApiV2010AccountMessage {
        ApiV2010AccountMessage {
            body: None,
            num_segments: None,
            direction: None,
            from: None,
            to: None,
            date_updated: None,
            price: None,
            error_message: None,
            uri: None,
            account_sid: None,
            num_media: None,
            status: None,
            messaging_service_sid: None,
            sid: None,
            date_sent: None,
            date_created: None,
            error_code: None,
            price_unit: None,
            api_version: None,
            subresource_uris: None,
        }
    }
}


